### PR TITLE
Create Readme4.md

### PR DESCRIPTION
**Pull request by tarball3y**
Hello ! I want to introduce the new concept of Readme4

### CODE REVIEW

**Comment by chainventive** [comment]
Yeah ! Great idea ! We will integrate it !

**Comment by tarball3y** [comment]
Hi tarball3y, before accepting your pull request please update the readme title in order to fully meets the one of those existing.

**Comment by chainventive** [comment]
Hi tarball3y, before accepting your pull request please update the readme title in order to fully meets the one of those existing.

**Comment by tarball3y** [comment]
Hello ! Readme4 title updated !

**Comment by tarball3y** [comment]
Hi ! Last thing, please update all readme title format with single "#" instead of double "##"

**Comment by chainventive** [comment]
Hi ! Last thing, please update all readme title format with single "#" instead of double "##"

**Comment by tarball3y** [comment]
done !

**Comment by chainventive** [comment]
Many thanks !

**Comment by chainventive** [comment]
Merged ! Thank you !

**Pull request merged**
